export const LOGING_SUCCESS = 'LOGING_SUCCESS';
export const GET_CHATLIST = 'GET_CHATLIST';
export const GET_CHATMESSAGE = 'GET_CHATMESSAGE';
export const GET_FRIENDLIST = 'GET_FRIENDLIST';
export const CLEAR_CHATPANEL = 'CLEAR_CHATPANEL';
