export const LOGING_SUCCESS = 'LOGING_SUCCESS';
export const GET_CHATLIST = 'GET_CHATLIST';
export const GET_CHATMESSAGE = 'GET_CHATMESSAGE';
export const GET_FRIENDLIST = 'GET_FRIENDLIST';
export const ADD_NEWMESSAGE = 'ADD_NEWMESSAGE';
export const UPDATE_CHATLIST = 'UPDATE_CHATLIST';
export const ACTIVE_CHAT = 'ACTIVE_CHAT';
